## FOR TEXT DATAS 


In [1]:
# SUPERVISED ALGORITHM 
# NAIVE BAYES
#HIGH BIAS AND LOW VARIANCE \ 


## NAIVE BAYES

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
data = pd.read_csv('dataset/app_review.csv')
data.head()

package_name                                             review  \
0  com.facebook.katana   privacy at least put some option appear offli...   
1  com.facebook.katana   messenger issues ever since the last update, ...   
2  com.facebook.katana   profile any time my wife or anybody has more ...   
3  com.facebook.katana   the new features suck for those of us who don...   
4  com.facebook.katana   forced reload on uploading pic on replying co...   

   polarity  
0         0  
1         0  
2         0  
3         0  
4         0

In [4]:
def preprocess_data(data):
    # Remove package name as it's not relevant
    data = data.drop('package_name', axis=1)
    # convrt txt to lowercase
    # strip - removes whitesapces in first or last spaces in data
    data['review']=data['review'].str.strip().str.lower()
    return data
data = preprocess_data(data)
data.head()

review  polarity
0  privacy at least put some option appear offlin...         0
1  messenger issues ever since the last update, i...         0
2  profile any time my wife or anybody has more t...         0
3  the new features suck for those of us who don'...         0
4  forced reload on uploading pic on replying com...         0

In [5]:
#split into training and testing
x = data['review'] 
y = data['polarity']
x,x_test,y,y_test = train_test_split(x,y, stratify=y, test_size=0.25,random_state=42)

# stratify - for balancing the training and testing


In [6]:
# Vectorize text reviews to numbersa
vec = CountVectorizer(stop_words='english')
x = vec.fit_transform(x).toarray()
x_test = vec.transform(x_test).toarray()

In [7]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x,y)

MultinomialNB()

In [8]:
model.score(x_test,y_test)

0.8565022421524664

### SENTIMENT ANALYSIS classifiaction

In [9]:
model.predict(vec.transform(['Love this app simply awesome!']))

array([1], dtype=int64)

In [10]:
model.predict(vec.transform(["It's getting stuck a lot while using this app"]))

array([0], dtype=int64)

In [11]:
print(model.score(x_test,y_test))
print(model.predict(vec.transform(['Love this app simply awesome!'])))
print(model.predict(vec.transform(["It's getting stuck a lot while using this app"])))

0.8565022421524664
[1]
[0]


## DECISION TREES

In [12]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier# import Decision TreeClassier
from sklearn.model_selection import train_test_split #import train_test_split
from sklearn import metrics # accuracy calculator


In [13]:
col_names = ['pregnant','glucose','bp','skin','insulin','bmi','pedigree','age','label']
#load dataset
pima = pd.read_csv("dataset/pima-indians-diabetes.csv",header=None,names=col_names)
pima.head()

pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0         6      148  72    35        0  33.6     0.627   50      1
1         1       85  66    29        0  26.6     0.351   31      0
2         8      183  64     0        0  23.3     0.672   32      1
3         1       89  66    23       94  28.1     0.167   21      0
4         0      137  40    35      168  43.1     2.288   33      1

In [14]:
feature_cols = ['pregnant','insulin','bmi','age','glucose','bp','pedigree']
x=pima[feature_cols ] # features
y=pima.label # target variable
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=1)  # 70% training and 30% testing

In [15]:
clf = DecisionTreeClassifier()
clf = clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

Accuracy: 0.6666666666666666


In [16]:
clf = DecisionTreeClassifier(criterion="entropy", max_depth=3)
clf = clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

Accuracy: 0.7705627705627706


## RANDOM FOREST

In [17]:
from sklearn import datasets
iris = datasets.load_iris()

In [18]:
data.head()

review  polarity
0  privacy at least put some option appear offlin...         0
1  messenger issues ever since the last update, i...         0
2  profile any time my wife or anybody has more t...         0
3  the new features suck for those of us who don'...         0
4  forced reload on uploading pic on replying com...         0

In [19]:
# Creating a dataframe of given iris dataset.
import pandas as pd
data = pd.DataFrame({
    'sepal length':iris.data[:,0],
    'sepal width' :iris.data[:,1],
    'petal length' :iris.data[:,2],
    'petal width' :iris.data[:,3],
    'species' :iris.target
})
data.head()

sepal length  sepal width  petal length  petal width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [20]:
#Import train_test_split function
from sklearn.model_selection import train_test_split
X=data[['sepal length','sepal width','petal length','petal width']]
y=data['species'] # labels
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.3)

In [21]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)

In [22]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

Accuracy: 0.9333333333333333


## K-NEAREST NEIGHBOR

In [23]:
#LAZY LEARNING

In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [25]:
data=pd.read_csv('dataset/User_Data.csv')
x=data.iloc[:,[2,3]].values
y=data.iloc[:,4].values
print(x[:10])

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]]


In [26]:
#extracting independent and dependent variable
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [27]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc_x= StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)
print(x_train[:10])
x_test=sc_x.transform(x_test)


[[ 9.79055254e-02  1.06878203e+00]
 [ 2.14030556e+00 -1.05092156e+00]
 [-1.55546593e+00 -1.52196681e+00]
 [ 3.89676959e-01 -4.62115010e-01]
 [ 9.79055254e-02  1.89311120e+00]
 [ 1.36224840e+00  5.97736786e-01]
 [ 6.48380963e-04 -2.56032716e-01]
 [ 2.04304841e+00 -8.15398942e-01]
 [ 8.75962681e-01 -7.85958614e-01]
 [-1.94449451e+00  3.62214165e-01]]


In [28]:
# Fitting K-NN classifier to the training set
# metrics - minkowski,euclidean distance,manhattan

from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5, metric='minkowski',p=2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [29]:
# predicting the test set result
y_pred=classifier.predict(x_test)

In [30]:
#Creating the confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)

In [31]:
cm

array([[62,  0],
       [38,  0]], dtype=int64)

In [32]:
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(y_test,y_pred))
      

Accuracy: 0.62


In [33]:
from sklearn.metrics import precision_score
print("Precision:",precision_score(y_test,y_pred))

Precision: 0.0


C:\Users\INTEL\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [37]:
# MANHATTAN
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5, metric='manhattan',p=2)
classifier.fit(x_train, y_train)

KNeighborsClassifier(metric='manhattan')

In [36]:
# EUCLIDEAN
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5, metric='euclidean',p=2)
classifier.fit(x_train, y_train)

KNeighborsClassifier(metric='euclidean')