In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

C:\Users\kannan\OneDrive\Documents\Python Scripts\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\kannan\OneDrive\Documents\Python Scripts\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.4' currently installed).
  from pandas.core import (


In [3]:
data=pd.read_csv('data/User_Data.csv')
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
# replace the data using map
data['Gender']=data['Gender'].map({'Male':0,'Female':1}).astype(int)
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       0   19            19000          0
1    15810944       0   35            20000          0
2    15668575       1   26            43000          0
3    15603246       1   27            57000          0
4    15804002       0   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       1   46            41000          1
396  15706071       0   51            23000          1
397  15654296       1   50            20000          1
398  15755018       0   36            33000          0
399  15594041       1   49            36000          1

[400 rows x 5 columns]

In [6]:
from sklearn.model_selection import train_test_split
xtrain, xtest,ytrain,ytest = train_test_split(x ,y,test_size = 0.25)

In [14]:
# standardscalar model accuracy - for numeric data
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
xtrain = sc_x.fit_transform(xtrain)
xtest = sc_x.transform(xtest)

print (xtrain[0:10, :])
print (xtest[0:10, :])

[[-5.86834250e-01  1.51112161e+00]
 [-2.97595025e-01 -1.45186194e+00]
 [-1.06889962e+00  4.44447533e-01]
 [ 2.80883425e-01  8.88895067e-02]
 [-8.76073475e-01 -6.51856382e-01]
 [ 8.59361875e-01 -5.92596711e-01]
 [ 6.66535725e-01 -1.09630392e+00]
 [ 9.55774950e-01 -1.18519342e+00]
 [-4.90421175e-01 -5.18104078e-18]
 [ 1.34142725e+00  2.40001668e+00]]
[[-0.7796604   1.95556915]
 [ 0.85936188  2.22223767]
 [-1.9366173   0.38518786]
 [-0.20118195  0.88889507]
 [ 0.28088343  0.08888951]
 [-0.29759502  0.08888951]
 [-0.68324732  1.45186194]
 [-0.29759502 -1.36297244]
 [-0.0083558  -0.53333704]
 [-1.84020423 -1.42223211]]


In [15]:
#LOGISTIC REGRESSION

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(xtrain, ytrain)

LogisticRegression(random_state=0)

In [16]:
y_pred = classifier.predict(xtest)
y_pred

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1], dtype=int64)

In [13]:
from sklearn.metrics import accuracy_score
print("Accuracy : ",accuracy_score(ytest, y_pred))

Accuracy :  0.86
