In [1]:
# LAZY LEARNING

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

C:\Users\kannan\OneDrive\Documents\Python Scripts\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\kannan\OneDrive\Documents\Python Scripts\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.4' currently installed).
  from pandas.core import (


In [3]:
data=pd.read_csv('data/User_Data.csv')
x=data.iloc[:,[2,3]].values
y=data.iloc[:,4].values
print(x[:10])

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]]


In [4]:
#extracting independent and dependent variable
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

C:\Users\kannan\OneDrive\Documents\Python Scripts\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [5]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc_x= StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)
print(x_train[:10])
x_test=sc_x.transform(x_test)


[[-0.97126723 -1.58149157]
 [ 0.93567105 -0.59889043]
 [-1.16196106 -1.43261261]
 [-0.20849192 -0.3606841 ]
 [-0.20849192 -0.50956306]
 [ 1.12636488  0.47303808]
 [-1.63869563 -1.01575152]
 [-0.87592032 -0.3309083 ]
 [-0.20849192 -1.28373365]
 [ 0.45893648 -0.50956306]]


In [6]:
# Fitting K-NN classifier to the training set
# metrics - minkowski,euclidean distance,manhattan

from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5, metric='minkowski',p=2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [7]:
# predicting the test set result
y_pred=classifier.predict(x_test)


In [8]:
#Creating the confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)

In [9]:
cm

array([[58,  0],
       [42,  0]], dtype=int64)

In [10]:
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(y_test,y_pred))
      

Accuracy: 0.58


In [11]:
from sklearn.metrics import precision_score
print("Precision:",precision_score(y_test,y_pred))

Precision: 0.0


C:\Users\kannan\OneDrive\Documents\Python Scripts\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [12]:
# METRICS

# MANHATTAN
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5, metric='manhattan',p=2)
classifier.fit(x_train, y_train)

KNeighborsClassifier(metric='manhattan')

In [13]:
# EUCLIDEAN
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5, metric='euclidean',p=2)
classifier.fit(x_train, y_train)

KNeighborsClassifier(metric='euclidean')